const technologies = [
  { name: "HTML", id: 1 },
  { name: "CSS", id: 2 },
  { name: "JavaScript", id: 3 },
  { name: "TypeScript", id: 4 },
  { name: "React", id: 5 },
  { name: "Tailwind", id: 6 },
  { name: "Next.js", id: 7 },
  { name: "Sass", id: 8 },
  { name: "Node.js", id: 9 },
  { name: "Express", id: 10 },
  { name: "PostgreSQL", id: 11 },
  { name: "MySQL", id: 12 },
  { name: "MongoDB", id: 13 },
  { name: "SQLite", id: 14 },
  { name: "GraphQL", id: 15 },
  { name: "Redux", id: 16 },
  { name: "Apollo", id: 17 },
  { name: "Vue.js", id: 18 },
  { name: "Angular", id: 19 },
  { name: "Docker", id: 20 },
  { name: "Kubernetes", id: 21 },
  { name: "AWS", id: 22 },
  { name: "Azure", id: 23 },
  { name: "Google Cloud", id: 24 },
  { name: "Jenkins", id: 25 },
  { name: "Git", id: 26 },
  { name: "GitHub", id: 27 },
  { name: "GitLab", id: 28 },
  { name: "CI/CD", id: 29 },
  { name: "Webpack", id: 30 },
  { name: "Babel", id: 31 },
  { name: "ESLint", id: 32 },
  { name: "Prettier", id: 33 },
  { name: "Mocha", id: 34 },
  { name: "Jest", id: 35 },
  { name: "Cypress", id: 36 },
  { name: "Puppeteer", id: 37 },
  { name: "Chai", id: 38 },
  { name: "PHP", id: 39 },
  { name: "Laravel", id: 40 },
  { name: "Symfony", id: 41 },
  { name: "Flask", id: 42 },
  { name: "Django", id: 43 },
  { name: "Ruby on Rails", id: 44 },
  { name: "Rust", id: 45 },
  { name: "Go", id: 46 },
  { name: "C", id: 47 },
  { name: "C++", id: 48 },
  { name: "C#", id: 49 },
  { name: ".NET", id: 50 },
  { name: "Java", id: 51 },
  { name: "Spring Boot", id: 52 },
  { name: "Kotlin", id: 53 },
  { name: "Swift", id: 54 },
  { name: "Objective-C", id: 55 },
  { name: "Flutter", id: 56 },
  { name: "Dart", id: 57 },
  { name: "Xamarin", id: 58 },
  { name: "React Native", id: 59 },
  { name: "Ionic", id: 60 },
  { name: "Bootstrap", id: 61 },
  { name: "Material UI", id: 62 },
  { name: "Ant Design", id: 63 },
  { name: "Foundation", id: 64 },
  { name: "Bulma", id: 65 },
  { name: "Figma", id: 66 },
  { name: "Sketch", id: 67 },
  { name: "Adobe XD", id: 68 },
  { name: "Photoshop", id: 69 },
  { name: "Illustrator", id: 70 },
  { name: "Inkscape", id: 71 },
  { name: "Blender", id: 72 },
  { name: "WebAssembly", id: 73 },
  { name: "Three.js", id: 74 },
  { name: "D3.js", id: 75 },
  { name: "TensorFlow", id: 76 },
  { name: "PyTorch", id: 77 },
  { name: "Pandas", id: 78 },
  { name: "NumPy", id: 79 },
  { name: "Scikit-learn", id: 80 },
  { name: "Matplotlib", id: 81 },
  { name: "Seaborn", id: 82 },
  { name: "OpenCV", id: 83 },
  { name: "Keras", id: 84 },
  { name: "NLP", id: 85 },
  { name: "Hadoop", id: 86 },
  { name: "Spark", id: 87 },
  { name: "Kafka", id: 88 },
  { name: "Elasticsearch", id: 89 },
  { name: "Logstash", id: 90 },
  { name: "Kibana", id: 91 },
  { name: "Prometheus", id: 92 },
  { name: "Grafana", id: 93 },
  { name: "Terraform", id: 94 },
  { name: "Ansible", id: 95 },
  { name: "Chef", id: 96 },
  { name: "Puppet", id: 97 },
  { name: "Vagrant", id: 98 },
  { name: "Electron", id: 99 },
  { name: "Svelte", id: 100 },
  { name: "Ember.js", id: 101 },
  { name: "Backbone.js", id: 102 },
];

export default technologies;
