import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import StoreProvider from "./storeProvider";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider >
      <ClerkProvider>
        <html lang="en">
          <body className="bg-primary">
            <Header />

            {children}

            <Footer />
          </body>
        </html>
      </ClerkProvider>
    </StoreProvider>
  );
};
